import Head from 'next/head'
import Image from 'next/image'
import Header from '@/components/header/header'
import Slider from '@/components/home/slider/slider'
import Product from '@/components/home/product/product'
import VideoAll from '@/components/home/videoAll/videoAll'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Slider />
        <Product />
        <VideoAll />
      </main>
    </>
  )
}
